set search_path to public;
CREATE TABLE ANIMAL (
    ANIMAL_ID SERIAL NOT NULL,
	TAG VARCHAR(9) NOT NULL,
	PARENTTAG VARCHAR(9),
	BIRTHDATE DATE,
	RACE VARCHAR(20),
	ISNATIVE VARCHAR(1) NOT NULL,
	WEIGHT NUMERIC(4,2),
	CONSTRAINT PK_ANIMAL PRIMARY KEY (ANIMAL_ID)

);